first_app/urls.py
from django.conf.urls import url
from first_app import views

# TEMPLATE TAGGING
app_name= 'first_app'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^other/', views.other, name='other'),
    url(r'^relative/', views.relative, name='relative'),
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    ]

first_project/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.conf.urls import include
from django.urls import path
from first_app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^formpage/',views.form_name_view, name='form'),
    url(r'^first_app/', include('first_app.urls')),
#    url(r'^other/', include('first_app.urls')),
#    url(r'^relative/', include('first_app.urls')),
    path('admin/', admin.site.urls),
    url(r'^logout/$',views.user_logout, name='logout'),
    url(r'^special/$',views.special, name='special'),

]

first_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic (models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name

class Webpage (models.Model):
    topic = models.ForeignKey(Topic, default=1, on_delete=models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, default=1, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

#---------------------------------------------------------------

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, default=1, on_delete=models.CASCADE)

    # additional classes
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

first_app/forms.py
from django import forms
from django.forms import ValidationError
from django.core import validators
from django.contrib.auth.models import User
from first_app.models import UserProfileInfo



class FormName(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label='Enter your email again')
    text = forms.CharField(widget=forms.Textarea)

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError("emails don't match")

#-------------------------------------------------------------------
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import AccessRecord, Topic, Webpage, UserProfileInfo
from  . import forms
from first_app.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    webpages_list=AccessRecord.objects.order_by('date')
    date_dict={'access_records':webpages_list}
    context_dict={
    'text':'Hello Again',
    'number': 100
    }
    return render(request, 'first_app/index.html',
    context=date_dict)

@login_required
def special(request):
    return HttpResponse('You are logged in')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def form_name_view(request):
    form = forms.FormName()

    if request.method=='POST':
        form=forms.FormName(request.POST)

        if form.is_valid():
            # do smth with the data
            print('validation success')
            print('Name:' +form.cleaned_data['name'])
            print('Email:' +form.cleaned_data['email'])
            print('Text:' +form.cleaned_data['text'])

    return render(request, 'first_app/form.html',{'form':form})

def other(request):
    return render(request,'first_app/other.html')

def relative(request):
    return render(request,'first_app/relative_url_template.html')

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else: # http request
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'first_app/registration.html',
    {'user_form':user_form,
     'profile_form':profile_form,
     'registered':registered})

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print('someone tried to login and failed :(')
            print('username: {} password: {}'.format(username,password))
            return HttpResponse('invalid login details supplied')

    else:
        return render(request,'first_app/login.html',{})

templates/first_app/base.html
<!DOCTYPE html>
<!--{% load static %}-->
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!--link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"-->
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><a class="navbar-brand" href="{% url 'index' %}">HOME</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'first_app:other' %}">other</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'first_app:register' %}">Register</a></li>

          {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li class="nav-item"><a class="nav-link" href="{% url 'first_app:user_login' %}">Login</a></li>

          {% endif %}


        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      <!-- everything outside here will be inherited if extended-->
      {% endblock %}
    </div>
  </body>
</html>

templates/first_app/form.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta charset="utf-8">
    <title>Form</title>
  </head>
  <body>
    <h1>Fill out the form</h1>
      <div class='container'>
        <form method="POST">
          {{form.as_p}}
          {% csrf_token %}
          <input type="submit" class="btn btn-primary" value="Submit">
        </form>
      </div>
  </body>
</html>

templates/first_app/index.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% load my_extras %}
  {% block body_block %}
  {% if request.user.is_authenticated %}
   <h1>Hi Welcome {{ request.user.username }}</h1>
{% else %}
<h1>Hi Welcome</h1>
{% endif %}
    <h2>here are your records</h2>
    <h3>Go to /formpage to fill out the form</h3>
    <a href="{% url 'first_app:other' %}">The other page</a>
    <h3>
      {{text|cut:'Again'}}
      {{number|add:300}}
    </h3>
    <div class="djangotwo">
      {% if access_records %}
      <table>
        <thead>
          <th>Site Name</th>
          <th>Date Accessed</th>
        </thead>
        {% for i in access_records %}
          <tr>
              <td>{{i.name}}</td>
              <td>{{i.date}}</td>
          </tr>
          {% endfor %}
      </table>
      {% else %}
          <p>no records found</p>
        {% endif %}
      </div>
      {% endblock %}

templates/first_app/login.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
  {% block body_block %}
<div class="jumbotron">
<h1>Please Login</h1>
<form action="{% url 'first_app:user_login' %}" method="post">
  {% csrf_token %}
  <label for="username">Username:</label>
  <input type="text" name="username" placeholder="Enter Username"="">
  <label for="password">Password</label>
  <input type="password" name="password" >

  <input type="submit" name="" value="Login">
</form>
</div>

  {% endblock %}

templates/first_app/other.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
{% block body_block %}
    <h1>Welcome to other</h1>
    <h2>ex of template inheritance</h2>
{% endblock %}

templates/first_app/registration.html
<!DOCTYPE html>
{% extends "first_app/base.html" %}
  {% block body_block %}
<div class="jumbotron">
  {% if registered %}
    <h1>Thank you for registering.</h1>
    {% else %}
    <h1>Register Here</h1>
    <h3>Please fill out the form:</h3>
    <form method="POST" enctype="multipart/form-data">
       {% csrf_token %}
       {{ user_form.as_p }}
       {{ profile_form.as_p }}
       <input type="submit" name="" value="Register">
    </form>
  {% endif %}

</div>
{% endblock %}

templates/first_app/relative_url_template.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div >
<h1>Welcome to relative url template</h1>
<a href="{% url 'first_app:other' %}">The other page</a>
</br>
<a href="{% url 'admin:index' %}">admin</a>
</br>
<a href="{% url 'index' %}">index</a>
    </div>
  </body>
</html>